import sqlite3
import time
import os

from datetime import datetime
import logging
import pandas as pd
from collections import deque

logger = logging.getLogger("vault")



class Database:
    def __init__(self, db_path):
        """
        Constructor for the Database class. 
        CRITICAL: Ensure there are exactly two underscores on each side of __init__.
        """
        self.db_path = db_path
        
        # This print helps us verify the constructor is actually running
        print(f"DEBUG: Initializing Database connection to: {self.db_path}")
        
        try:
            # check_same_thread=False allows both Oracle and Broker to use this connection
            self.conn = sqlite3.connect(self.db_path, check_same_thread=False)
            
            # This allows us to access rows like dictionaries: signal['price'] instead of signal[3]
            self.conn.row_factory = sqlite3.Row
            
            # Ensure tables exist
            self.create_tables()
            print("DEBUG: Database connection and tables verified successfully.")
            
        except Exception as e:
            print(f"❌ CRITICAL ERROR during DB init: {e}")

    def create_tables(self):
        """Creates the necessary tables if they do not exist."""
        cursor = self.conn.cursor()
        
        # Signals Table (for Broker alerts)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS signals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT,
                direction TEXT,
                price REAL,
                confidence REAL,
                warning TEXT,
                processed INTEGER DEFAULT 0,
                timestamp REAL
            )
        """)
        
        # Candles Table (for Historian/Oracle memory)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS candles (
                exchange TEXT,
                symbol TEXT,
                tf TEXT,
                ts INTEGER,
                open REAL,
                high REAL,
                low REAL,
                close REAL,
                volume REAL,
                is_closed INTEGER,
                PRIMARY KEY (symbol, tf, ts)
            )
        """)
        self.conn.commit()
    
    def load_candles(self, symbol, tf, limit=1000):
        """
        Loads historical candles to warm up the Oracle's memory buffers.
        Returns them in chronological order (oldest to newest).
        """
        query = "SELECT * FROM candles WHERE symbol = ? AND tf = ? ORDER BY ts DESC LIMIT ?"
        try:
            cursor = self.conn.cursor()
            cursor.execute(query, (symbol, tf, limit))
            # We fetch DESC (newest first) to get the most recent data, 
            # then we reverse it so indicators calculate correctly (oldest to newest).
            rows = cursor.fetchall()
            return [dict(row) for row in reversed(rows)]
        except Exception as e:
            print(f"❌ Error loading candles for {symbol}: {e}")
            return []

    def save_signal(self, symbol, direction, price, confidence, warning="No specific warnings."):
        """Saves a new signal generated by the Oracle."""
        query = """
            INSERT INTO signals (symbol, direction, price, confidence, warning, processed, timestamp)
            VALUES (?, ?, ?, ?, ?, 0, ?)
        """
        try:
            cursor = self.conn.cursor()
            cursor.execute(query, (symbol, direction, price, confidence, warning, time.time()))
            self.conn.commit()
        except Exception as e:
            print(f"❌ Error saving signal: {e}")

    def get_unprocessed_signals(self):
        """Fetches all signals that the Broker hasn't sent to WhatsApp yet."""
        # Double-check that connection exists before querying
        if not hasattr(self, 'conn'):
            print("❌ ERROR: Connection object 'conn' is missing in get_unprocessed_signals!")
            return []
            
        query = "SELECT * FROM signals WHERE processed = 0 ORDER BY timestamp ASC"
        try:
            cursor = self.conn.cursor()
            cursor.execute(query)
            # Convert rows to dictionaries so Broker can use signal['column_name']
            return [dict(row) for row in cursor.fetchall()]
        except Exception as e:
            print(f"❌ Error fetching signals: {e}")
            return []

    def mark_signal_processed(self, signal_id):
        """Marks a specific signal as processed so it won't be alerted again."""
        query = "UPDATE signals SET processed = 1 WHERE id = ?"
        try:
            cursor = self.conn.cursor()
            cursor.execute(query, (signal_id,))
            self.conn.commit()
            return True
        except Exception as e:
            print(f"❌ Error marking signal {signal_id} as processed: {e}")
            return False

    def get_latest_timestamp(self, symbol, tf):
        """Helper for Historian to find the last candle we downloaded."""
        query = "SELECT MAX(ts) FROM candles WHERE symbol = ? AND tf = ?"
        try:
            cursor = self.conn.cursor()
            cursor.execute(query, (symbol, tf))
            res = cursor.fetchone()[0]
            return res if res else 0
        except:
            return 0

    def save_candle(self, c):
        """Saves a candle from the Historian or Oracle."""
        query = """
            INSERT OR REPLACE INTO candles (exchange, symbol, tf, ts, open, high, low, close, volume, is_closed)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """
        try:
            cursor = self.conn.cursor()
            cursor.execute(query, (
                c['exchange'], c['symbol'], c['tf'], c['ts'], 
                c['open'], c['high'], c['low'], c['close'], c['volume'], int(c['is_closed'])
            ))
            self.conn.commit()
        except Exception as e:
            print(f"❌ Error saving candle: {e}")


class RingBuffer:
    """
    A sliding window of candles kept in RAM.
    Used by the Oracle to perform real-time technical analysis on the latest data.
    """
    def __init__(self, capacity=100):
        self.capacity = capacity
        self.data = deque(maxlen=capacity)

    def add(self, candle: dict):
        """Adds a candle to the buffer. If timestamp matches last entry, updates it."""
        if self.data and self.data[-1]['ts'] == candle['ts']:
            self.data[-1] = candle  
        else:
            self.data.append(candle)

    def get_df(self):
        """Converts the raw buffer data into a Pandas DataFrame for the SignalScorer."""
        if not self.data:
            return pd.DataFrame()
        return pd.DataFrame(list(self.data))

    def __len__(self):
        return len(self.data)